version: '3.8'

services:
  mysql:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql8_network
    environment:
      - MYSQL_ROOT_PASSWORD=Pikr@1991
      - TZ=Asia/Calcutta
networks:
  mysql8_network:
    driver: bridge