app:
  fusionauth:
    applicationId: e9fdb985-9173-4e01-9d73-ac2d60d1dc8e
    apiKey: ByUWjhASM3vPGGR8QxVLbQwXGunXxnsQFEfqsfmFxr34yEjVsD
    baseUrl: http://localhost:9011
    issuer: http://localhost:9011
  log:
    location: ./logs
    file_name: oauth2

server:
  port: 8081