spring:
  application:
    name: user-service
  datasource:
    username: ${spring.datasource.db.user:root}
    url: jdbc:mysql://${spring.datasource.db.host:localhost}:3306/${spring.datasource.default_schema:learning_ms}?createDatabaseIfNotExist=true
    password: ${spring.datasource.db.password:Pikr@1991}
  jpa:
    open-in-view: false
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){yellow} %clr(:){red} %clr(%m){faint}%n" # (3)

management:
  endpoints:
    web:
      exposure:
        include: '*'
metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true
tracing:
  sampling:
    probability: 1.0