

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: sample-ms
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'

server:
  port: 9000
  servlet:
    context-path: /sample-ms

# Actuator management configuration
management:
  server:
    base-path: /sample-ms
    port: 9001
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: threaddump



