server:
  port: 80

spring:
  datasource:
    username: root
    url: jdbc:mysql://192.168.48.2:3306/video_player?createDatabaseIfNotExist=true
    password: Pikr@1991
  jpa:
    open-in-view: false
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

logging:
  level:
    project:
      user:
        UserClient: DEBUG

feign:
  url: https://www.googleapis.com/youtube/v3
  client:
    config:
      default:
        connectTimeout: 500000
        readTimeout: 500000
        loggerLevel: full

youtube:
  channels:
    box:
      key: AIzaSyCtzaaUZWaiK9DxKvzMcjtXekb02yXBqRE
      channelId: UCS5AAtw7E2TmD0X8sw6czeQ
      name: What is in the box ?
    world:
      key: AIzaSyCMxL_WlG_hghJ4AvGBRUYwXQU_D-_e7Ug
      channelId: UCGNfPOCD69vlOu6aSSzd_5w
      name: World Of Roma😇🥰
  api:
    part: snippet,id
    order: date
    type: video
    duration_part: snippet,contentDetails,player
    max_results: 50