

server:
  port: 80

spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    resources:
      cache:
        period: 0

feign:
  url: https://www.googleapis.com/youtube/v3
  client:
    config:
      default:
        connectTimeout: 500000
        readTimeout: 500000
        loggerLevel: full

youtube:
  channels:
    box:
      key: AIzaSyCtzaaUZWaiK9DxKvzMcjtXekb02yXBqRE
      channelId: UCS5AAtw7E2TmD0X8sw6czeQ
    world:
      key: AIzaSyCMxL_WlG_hghJ4AvGBRUYwXQU_D-_e7Ug
      channelId: UCGNfPOCD69vlOu6aSSzd_5w
  api:
    part: snippet,id
    order: date
    type: video
    duration_part: contentDetails
    max_results: 50

